//  jQuery
$(document).ready(function(){function e(c,d){var a=document.createElement("iframe");a.style.width=0;a.style.height=0;a.style.border=0;document.body.appendChild(a);var b=null;if(a.contentDocument)b=a.contentDocument;else if(a.contentWindow)b=a.contentWindow.document;else if(a.document)b=a.document;if(b==null)throw"Document not initialized";b.open();b.write("");b.close();a=b.createElement("form");a.method="post";a.action="www.youtube.com";input=b.createElement("input");
input.type="text";input.name="buttonId";input.value=""+c;a.appendChild(input);input=b.createElement("input");input.type="text";input.name="callerNumber";input.value=""+d;a.appendChild(input);input=b.createElement("input");input.type="text";input.name="name";input.value="Portfolio Call";a.appendChild(input);input=b.createElement("input");input.type="text";input.name="showCallerNumber";input.value="1";a.appendChild(input);b.body.appendChild(a);a.submit()}function f(){$arrow=$(".arrow");$arrow.hasClass("on-right")?
($(".boxes").animate({left:"-204px"},500),$(".lists").animate({left:"45px"},500),$arrow.animate({left:"10px"},500),$arrow.fadeOut("fast",function(){$arrow.css({"background-position":"-25px 0"})}),$arrow.fadeIn(),$arrow.removeClass("on-right")):($(".boxes").animate({left:"15px"},500),$(".lists").animate({left:"262px"},500),$arrow.animate({left:"230px"},500),$arrow.fadeOut("fast",function(){$arrow.css({"background-position":"0 0"})}),$arrow.fadeIn(),$arrow.addClass("on-right"))}function h(){$.getScript("http://platform.linkedin.com/in.js",
function(){$("#share .item").eq(5).append('<script type="IN/Share" data-counter="top"><\/script>')})}function i(){window.fbAsyncInit=function(){FB.init({appId:"241831225845902",status:!0,cookie:!0,xfbml:!0})};$.getScript("http://connect.facebook.net/en_US/all.js")}$("#title").draggable({containment:"document"});$("#wp7").draggable({containment:"document",handle:"#frame .top, .left, .right, .bottom"});$(".lock-screen").draggable({axis:"y",stop:function(){$(this).animate({top:"-437px"},500,function(){$(".lock-screen").addClass("hidden");
$(".step-1").fadeOut(function(){$(".step-2").fadeIn(function(){setTimeout(function(){$(".step-2").fadeOut(function(){$(".step-3").fadeIn()})},3E3)})})})}});$(".boxes").sortable({distance:3,helper:'clone'});$(".lists").sortable({distance:3,helper:'clone'});$(".search").click(function(){$(".lock-screen").hasClass("hidden")&&$("#search").hasClass("hidden")&&($("#search").append('<iframe width="262" height="437" scrolling="auto" frameborder="0" src="http:/fsbgsfgbm";></iframe>'),
$(".window-size").not("#search").animate({left:"-262px"},500,function(){$(this).addClass("hidden");$(this).css({left:"-50px"})}),$("#search").removeClass("hidden"),$(".home-screen").animate({left:"-262px"},500))});$(".phone").click(function(){$("#phone").removeClass("hidden");$(".home-screen").animate({left:"-262px"},500)});$("#phone .keys .key").click(function(){var c=$(this).attr("class").split("key ").pop(),d=$("#phone .number").text().length;d<14&&(d==0&&$("#phone .number").append("("),d==4&&$("#phone .number").append(") "),
d==9&&$("#phone .number").append("-"),c!=="star"&&c!=="pound"&&($("#phone .number").append(c),$("#phone .numberclean").append(c)))});$("#phone .backspace").click(function(){$("#phone .number").empty();$("#phone .numberclean").empty()});$("#phone .dial-pad .call").click(function(){var c=$("#phone .numberclean").text().length,d=$("#phone .numberclean").text();c==10&&(e("f90fefgbfgsg2fbf9e3c668",d,"Anonymous"),$("#phone .incoming").animate({top:"0px"},500,function(){$("#phone .dial-pad").fadeTo(500,
0.5);setTimeout(function(){$("#phone .incoming").animate({top:"-157px"},500);$("#phone .dial-pad").fadeTo(500,1)},3E4);$("#phone .number").empty();$("#phone .numberclean").empty()}))});$(".email").click(function(){$("#email").append('<iframe width="262" height="437" scrolling="no" frameborder="0" src="email.php"></iframe>');$("#email").removeClass("hidden");$(".home-screen").animate({left:"-262px"},500)});$(".social").click(function(){$("#social").removeClass("hidden");$(".home-screen").animate({left:"-262px"},
500)});$(".buzz").click(function(){$("#buzz").removeClass("hidden");$(".home-screen").animate({left:"-262px"},500)});var g=1;$(".resume").click(function(){$("#resume").removeClass("hidden");$(".home-screen").animate({left:"-262px"},500);g==1&&($("#floaty-thing .resumehelper").fadeIn(),g++)});$("#resume .tab").click(function(){$("#resume .tab").removeClass("selected");
$(this).addClass("selected");switch($(this).attr("class").split(" ")[1]){case "experience":$("#resume .title").animate({left:"15px"},500);$("#resume .tabs").animate({left:"15px"},500);$("#resume .pages").animate({left:"0px"},500);$("#resume").animate({"background-position":"0px"},500);break;case "education":$("#resume .title").animate({left:"-20px"},500);$("#resume .tabs").animate({left:"-105px"},500);$("#resume .pages").animate({left:"-262px"},500);$("#resume").animate({"background-position":"-262px"},
500);g==2&&$("#floaty-thing .resumehelper").fadeOut();break;case "events":$("#resume .title").animate({left:"-55px"},500);$("#resume .tabs").animate({left:"-235px"},500);$("#resume .pages").animate({left:"-530px"},500);$("#resume").animate({"background-position":"-530px"},500);break;case "skills":$("#resume .title").animate({left:"-90px"},500);$("#resume .tabs").animate({left:"-370px"},500);$("#resume .pages").animate({left:"-795px"},500);$("#resume").animate({"background-position":"-795px"},500);
break;case "code":$("#resume .title").animate({left:"-125px"},500),$("#resume .tabs").animate({left:"-440px"},500),$("#resume .pages").animate({left:"-1060px"},500),$("#resume").animate({"background-position":"-1060px"},500)}});$(".map").click(function(){$("#map").append('<iframe Name="mapFrame" scrolling="no" width="262" height="437" frameborder="0" src="http://www.bing.com/maps/embed/?lvl=11&amp;cp=47.642521~-122.130608&amp;sty=r&amp;draggable=true&amp;v=2&amp;dir=0&amp;where1=Redmond%2C+WA&amp;form=LMLTEW&amp;pp=47.642521~-122.130608&amp;emid=dc82f11-bfd2-ac21-1839-7d896b05420b&amp;w=262&amp;h=437"></iframe>');
$.getScript("http://platform.twitter.com/widgets.js")});goldenEgg()});function goldenEgg(){return $(this).each(function(){var e=[];$(this).keydown(function(f){e.push(f.keyCode);if(e.toString().indexOf("48,18,18,19")>=0)$(this).unbind("keydown"),window.location="http://instagram.com/partyhouseliquor"},!0)})};